language: python
sudo: false

python:
  - "2.7"
  - "3.2"
  - "3.3"

# command to install dependencies
install: 
  - pip install nose

addons:
  apt:
    packages:
    - pylint
 
# command to run tests
script: 
  - pylint --rcfile=.pylint.config eagle-bom.py
  - nosetests test/
